Move config.build_production_command check inside assets.rake task
shakacode/react_on_rails pull request #1415
Opened 2021-12-29 02:30 UTC by Judahmeek

The only way I found to actually test the logic of `assets.rake` with an initialized Rails application was by using `bundle exec irb`

2021-12-29 02:33 UTC, Judahmeek reviewed
> *[Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1415)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[lib/tasks/assets.rake, line 12 at r1](https://reviewable.io/reviews/shakacode/react_on_rails/1415#-Ms30pqK67TyxeV6WPr9:-Ms30pqK67TyxeV6WPrA:b-6d7asc) ([raw file](https://github.com/shakacode/react_on_rails/blob/5fe6f53fed02e4689ad86fc9d30203da3c269a34/lib/tasks/assets.rake#L12)):*
> ```Ruby
> skip_react_on_rails_precompile = %w[no false n f].include?(ENV["REACT_ON_RAILS_PRECOMPILE"])
> 
> if !skip_react_on_rails_precompile && ReactOnRails.configuration.build_production_command.present?
> ```

I could not figure out how to access the Rails.application from inside this file, so my solution was to remove this check, always set `ENV["WEBPACKER_PRECOMPILE"] = "false"`, & then invoke the webpacker tasks if `build_production_command` isn't defined.


<!-- Sent from Reviewable.io -->

2021-12-29 02:35 UTC, Judahmeek reviewed
> *[Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1415)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[lib/tasks/assets.rake, line 12 at r1](https://reviewable.io/reviews/shakacode/react_on_rails/1415#-Ms30pqK67TyxeV6WPr9:-Ms31VrxDMYdrc0Rl7It:b6c3ddm) ([raw file](https://github.com/shakacode/react_on_rails/blob/5fe6f53fed02e4689ad86fc9d30203da3c269a34/lib/tasks/assets.rake#L12)):*
<details><summary><i>Previously, Judahmeek (Judah Meek) wrote…</i></summary><blockquote>

I could not figure out how to access the Rails.application from inside this file, so my solution was to remove this check, always set `ENV["WEBPACKER_PRECOMPILE"] = "false"`, & then invoke the webpacker tasks if `build_production_command` isn't defined.
</blockquote></details>

if `ENV["WEBPACKER_PRECOMPILE"] = "false"`, doesn't that mean that `webpacker:clobber` will be skipped as well?


<!-- Sent from Reviewable.io -->

2021-12-29 03:39 UTC, Judahmeek reviewed
> *[Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1415)* status: 0 of 3 files reviewed, 2 unresolved discussions

___
*[spec/dummy/config/initializers/react_on_rails.rb, line 23 at r2](https://reviewable.io/reviews/shakacode/react_on_rails/1415#-Ms3GBjhEsio9oyH84jS:-Ms3GBjhEsio9oyH84jT:bbxut12) ([raw file](https://github.com/shakacode/react_on_rails/blob/47fba9aa95c31829a5c4423dcab291d85ee10e20/spec/dummy/config/initializers/react_on_rails.rb#L23)):*
> ```Ruby
> 
>   # config.build_test_command = "yarn run build:test"
>   # config.build_production_command = "yarn run build:prod"
> ```

Should I uncomment this & then add a spec that confirms that `ENV["WEBPACKER_PRECOMPILE"]` is `false`?


<!-- Sent from Reviewable.io -->

2021-12-29 21:46 UTC, justin808 reviewed
> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1415)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @Judahmeek and @justin808)

___
*[spec/dummy/config/initializers/react_on_rails.rb, line 23 at r2](https://reviewable.io/reviews/shakacode/react_on_rails/1415#-Ms3GBjhEsio9oyH84jS:-Ms777sM73qKdCwV7J4x:bb77uf3) ([raw file](https://github.com/shakacode/react_on_rails/blob/47fba9aa95c31829a5c4423dcab291d85ee10e20/spec/dummy/config/initializers/react_on_rails.rb#L23)):*
<details><summary><i>Previously, Judahmeek (Judah Meek) wrote…</i></summary><blockquote>

Should I uncomment this & then add a spec that confirms that `ENV["WEBPACKER_PRECOMPILE"]` is `false`?
</blockquote></details>

Yes!


<!-- Sent from Reviewable.io -->

2021-12-29 22:53 UTC, justin808 requested changes
> Reviewed 3 of 6 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1415)* status: all files reviewed, 5 unresolved discussions (waiting on @Judahmeek and @justin808)

___
*[spec/dummy/config/initializers/react_on_rails.rb, line 23 at r5](https://reviewable.io/reviews/shakacode/react_on_rails/1415#-Ms7NfM06tTrTiA5aay1:-Ms7NfM06tTrTiA5aay2:b-pkl53y) ([raw file](https://github.com/shakacode/react_on_rails/blob/3802035dd95b27f6aed66ab701582f3e672bc4a0/spec/dummy/config/initializers/react_on_rails.rb#L23)):*
> ```Ruby
> 
>   # config.build_test_command = "yarn run build:test"
>   config.build_production_command = "echo 'ran ReactOnRails config.build_production_command'"
> ```

But this example then doesn't work...

@gscarv13 made this so it is deployed to heroku.

Let's keep as commented, with `bin/webpack` as the command that it runs.
___
*[spec/dummy/spec/initialized_configuration_spec.rb, line 7 at r5](https://reviewable.io/reviews/shakacode/react_on_rails/1415#-Ms7O60N-nhSsC64iTQ-:-Ms7O60OAgY3uqe9pKgT:b-ytavj) ([raw file](https://github.com/shakacode/react_on_rails/blob/3802035dd95b27f6aed66ab701582f3e672bc4a0/spec/dummy/spec/initialized_configuration_spec.rb#L7)):*
> ```Ruby
> describe "ReactOnRails initializer" do
>   it "changes ENV[\"WEBPACKER_PRECOMPILE\"] to \"false\" because config.build_production_command is defined" do
>     expect(ENV["WEBPACKER_PRECOMPILE"]).to eq("false")
> ```

we can move this to a unit test for config, see below
___
*[spec/react_on_rails/configuration_spec.rb, line 83 at r5](https://reviewable.io/reviews/shakacode/react_on_rails/1415#-Ms7OU_CEKZnix1WRejU:-Ms7OU_CEKZnix1WRejV:b-2ihldn) ([raw file](https://github.com/shakacode/react_on_rails/blob/3802035dd95b27f6aed66ab701582f3e672bc4a0/spec/react_on_rails/configuration_spec.rb#L83)):*
> ```Ruby
>         end
> 
>         ENV["WEBPACKER_PRECOMPILE"] = "false"
> ```

this test doesn't make sense

let's check both cases of set and not set


<!-- Sent from Reviewable.io -->

2021-12-29 22:54 UTC, justin808 reviewed
> *[Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1415)* status: all files reviewed, 5 unresolved discussions (waiting on @Judahmeek)

___
*[lib/tasks/assets.rake, line 12 at r1](https://reviewable.io/reviews/shakacode/react_on_rails/1415#-Ms30pqK67TyxeV6WPr9:-Ms7ObVBAr56l0IMeelf:b-u9q16t) ([raw file](https://github.com/shakacode/react_on_rails/blob/5fe6f53fed02e4689ad86fc9d30203da3c269a34/lib/tasks/assets.rake#L12)):*
<details><summary><i>Previously, Judahmeek (Judah Meek) wrote…</i></summary><blockquote>

if `ENV["WEBPACKER_PRECOMPILE"] = "false"`, doesn't that mean that `webpacker:clobber` will be skipped as well?
</blockquote></details>

yes, that's OK.


<!-- Sent from Reviewable.io -->

2021-12-29 23:20 UTC, Judahmeek reviewed
> *[Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1415)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @gscarv13 and @justin808)

___
*[spec/dummy/config/initializers/react_on_rails.rb, line 23 at r5](https://reviewable.io/reviews/shakacode/react_on_rails/1415#-Ms7NfM06tTrTiA5aay1:-Ms7UbJCENPUicOkaoAO:b-896fix) ([raw file](https://github.com/shakacode/react_on_rails/blob/3802035dd95b27f6aed66ab701582f3e672bc4a0/spec/dummy/config/initializers/react_on_rails.rb#L23)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

But this example then doesn't work...

@gscarv13 made this so it is deployed to heroku.

Let's keep as commented, with `bin/webpack` as the command that it runs.
</blockquote></details>

Done.
___
*[spec/react_on_rails/configuration_spec.rb, line 83 at r5](https://reviewable.io/reviews/shakacode/react_on_rails/1415#-Ms7OU_CEKZnix1WRejU:-Ms7TIrPAxPR5e6zz9pA:b-wmt8dm) ([raw file](https://github.com/shakacode/react_on_rails/blob/3802035dd95b27f6aed66ab701582f3e672bc4a0/spec/react_on_rails/configuration_spec.rb#L83)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

this test doesn't make sense

let's check both cases of set and not set
</blockquote></details>

My bad. Copied the wrong line there.

My latest commit does check both set & unset.

The first `expect` is while the `build_production_command` is unset & the second `expect` confirms that setting `build_production_command` results in ENV["WEBPACKER_PRECOMPILE"] being set to "false"
___
*[spec/dummy/spec/initialized_configuration_spec.rb, line 7 at r5](https://reviewable.io/reviews/shakacode/react_on_rails/1415#-Ms7O60N-nhSsC64iTQ-:-Ms7UXw62AhHFuDM220H:b-896fix) ([raw file](https://github.com/shakacode/react_on_rails/blob/3802035dd95b27f6aed66ab701582f3e672bc4a0/spec/dummy/spec/initialized_configuration_spec.rb#L7)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

we can move this to a unit test for config, see below
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-29 23:21 UTC, justin808 commented on spec/react_on_rails/configuration_spec.rb
> +      end
all the lines above 79-80 with nil and check that the value for the ENV is reset.

2021-12-30 00:17 UTC, justin808 commented on lib/react_on_rails/configuration.rb
> +      return unless !skip_react_on_rails_precompile && build_production_command.present?
```ruby
return if skip_react_on_rails_precompile || build_production_command.blank?
```

2021-12-30 02:51 UTC, justin808 approved these changes
> Reviewed 2 of 3 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1415)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Judahmeek)



<!-- Sent from Reviewable.io -->

2021-12-30 02:53 UTC, merged