Initial Implementation of RSC
shakacode/react_on_rails pull request #1573
Opened 2023-08-10 18:09 UTC by KhaledEmaraDev

### Summary

This is an initial implementation of React Server Components (RSC). In this PR:
1. I add the necessary code to render to the RSC wire format using Node.js Streams.
2. I add a hook `useRSC()` and a React Component that extends `react-router-dom`'s `Route` named `RSCRoute` to be used to route to RSC components.
3. I make sure to separate Server and Client functions because sometimes Server code requires somethings only available to Node.

### Pull Request checklist
_Remove this line after checking all the items here. If the item is not applicable to the PR, both check it out and wrap it by `~`._

- [ ] Add/update test to cover these changes
- [ ] Update documentation
- [ ] Update CHANGELOG file  
  _Add the CHANGELOG entry at the top of the file._

### Other Information

_Remove this paragraph and mention any other important and relevant information such as benchmarks._

2023-08-10 20:25 UTC, KhaledEmaraDev commented on node_package/src/renderReactServerComponent.ts
> +        const reactClientManifest = readFileSync(path.resolve(__dirname, 'react-client-manifest.json'), 'utf8');
This should only be read once and cached.
Shared across workers is better.

2023-10-13 16:15 UTC, ahangarha commented
Is this PR ready for review? If yes, May you please update the description to reflect the state of the PR?

2023-11-17 00:56 UTC, justin808 commented
@KhaledEmaraDev close this one?

2023-11-17 20:33 UTC, KhaledEmaraDev commented
@justin808 No, it's needed for the Pro version to work. I think it could be accepted as-is. I will not introduce new changes to it.

2023-11-23 02:05 UTC, justin808 requested changes

2023-11-23 02:05 UTC, justin808 commented on package.json
> +      "pre-commit": "yalc check"
why is this needed pre-commit?

2023-11-23 02:05 UTC, justin808 commented on package.json
> +    "husky": "^4.3.6",
husky and yalc should be separate PRs.

2023-11-23 02:05 UTC, justin808 commented on package.json
> +  },
@KhaledEmaraDev can you explain this?

Seems odd to start exporting everything from package.json

Why not add what's necessary to the current exports?

We already have:
https://github.com/shakacode/react_on_rails/blob/master/node_package/src/ReactOnRails.ts#L292-L293

2023-11-23 02:05 UTC, justin808 commented on yarn.lock
this file should not be changing, right?

2024-01-09 08:04 UTC, closed without merging